### ISSUE TITLE
这个能不能直接修改系统host

### ISSUE THREAD

**Issue by syymo** [imweb/lan-settings#7]
这个能不能直接修改系统host

**Comment by avwo** [comment]
不支持，设置host可以用 https://github.com/avwo/whistle

**Comment by syymo** [comment]
> 不支持，设置host可以用 https://github.com/avwo/whistle

感谢你的及时回复，whistle可能也不是我想要的最好解决办法，我再想想其他办法

**Comment by avwo** [comment]
看下switchhosts，不过直接改系统hosts会有受dns缓存影响，通过代理设置hosts是比较好的实践，功能更全

**Comment by syymo** [comment]
> 看下switchhosts，不过直接改系统hosts会有受dns缓存影响，通过代理设置hosts是比较好的实践，功能更全

确实修改系统hosts不是很好的方法，但是代理设置就把本来的问题复杂化了

**Comment by avwo** [comment]
代理不仅仅是设置hosts，还可以抓包，设置代理，修改请求响应数据，注入内容，本地替换等等
